FROM golang:1.24 AS builder
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/worker ./cmd/worker

FROM gcr.io/distroless/base-debian12
COPY --from=builder /bin/worker /usr/local/bin/worker
WORKDIR /data
ENTRYPOINT ["/usr/local/bin/worker"]
